### ISSUE TITLE
Login Page frontend needs to be enhanced

### ISSUE THREAD

**Issue by harshagrawal523** [harshagrawal523/Portfolyser#1]
The login page is very basic and just has the form element and nothing else. Please enhance the frontend of login page , nothing very fancy just minimal enhancement. Please keep these things in mind :-
- Tech Stack :- HTML / CSS / Bootstrap
-  If you have any doubts you can ask here only.
-  Please mention the issue name in your PR.

**Comment by letsintegreat** [comment]
I'd like to work on this issue.

**Comment by harshagrawal523** [comment]
> I'd like to work on this issue.

okay! go ahead
