### ISSUE TITLE
Add Experience Section in the Template

### ISSUE THREAD

**Issue by GunjanDhanuka** [harshagrawal523/Portfolyser#10]
The existing template is minimalistic and misses out on a few important things. Please add a section where you can add your work and education experience.

Corresponding to this, you also need to add fields in the form of the experiences.

Tasks:
1. Setup the project on your local system.
2. Get yourself assigned to the issue.
3. Add the Experience / Education section in the Template.
4. Add the forms for Experience/ Education.
5. Create a PR after testing it locally.

**Comment by shmiitg** [comment]
I would like to work on this issue. Please assign me

**Comment by harshagrawal523** [comment]
Okay!

**Comment by shmiitg** [comment]
The experience section referred here means the introduction form right?
![Screenshot (266)](https://user-images.githubusercontent.com/70333141/144899988-a4f3ade5-ebda-4aac-ad8b-16e7386e46b2.png)

**Comment by harshagrawal523** [comment]
> The experience section referred here means the introduction form right? ![Screenshot (266)](https://user-images.githubusercontent.com/70333141/144899988-a4f3ade5-ebda-4aac-ad8b-16e7386e46b2.png)

No you need to make a new form which takes details about your education background

**Comment by shmiitg** [comment]
it should be in a new route or in the same intro route?

**Comment by harshagrawal523** [comment]
> it should be in a new route or in the same intro route?

new route , for now it's fine if there is no button for it , we can manually write the url and open it . but something like 
/education should be there

**Comment by harshagrawal523** [comment]
> ok i got it

any updates?

**Comment by shmiitg** [comment]
yes i am working on it..by evening i will do it

**Comment by shmiitg** [comment]
![Screenshot (267)](https://user-images.githubusercontent.com/70333141/144991663-e573482f-b10a-416d-b864-a9bf7ea0f6fd.png)
I have created this template now (no styling only template). 
See if this works.
I am adding the schemas and post routes for this now

**Comment by shmiitg** [comment]
![Screenshot (268)](https://user-images.githubusercontent.com/70333141/144992664-50d6bb83-fe0f-4cd9-912f-c93d7693c7dc.png)
I have created this template by now
Check if this works.
I am currently updating the post route and creating the schema for work and education

![Screenshot (269)](https://user-images.githubusercontent.com/70333141/144992976-724e2d7c-11d2-44cd-8819-7080a5c6d5c7.png)
we can add more fields like this and remove them

**Comment by harshagrawal523** [comment]
This looks great , yes you can models related to it

**Comment by shmiitg** [comment]
I have sent you the pr ..please review it
