### ISSUE TITLE
No logout button in home page

### ISSUE THREAD

**Issue by harshagrawal523** [harshagrawal523/Portfolyser#18]
The existing home page has login and register links but the logout link is missing , add the logout link and if possible try to use if else statements in ejs so if a user is logged in then show only logout else show login. 

Tasks:

- Setup the project on your local system.
- Get yourself assigned to the issue.
- Add the required changes
- Create a PR after testing it locally.

**Comment by SudhansuuRanjan** [comment]
I want  to work on it . Assign it to me.

**Comment by shmiitg** [comment]
I am working on the home page ui. I will do this also

**Comment by harshagrawal523** [comment]
> I want to work on it . Assign it to me.

Hi @SudhansuuRanjan ! You can try some other issues ..
