### ISSUE TITLE
Register Page frontend needs to be enhanced 

### ISSUE THREAD

**Issue by harshagrawal523** [harshagrawal523/Portfolyser#2]
The Register page is very basic and just has the form element and nothing else. Please enhance the frontend of Register page , nothing very fancy just minimal enhancement. Please keep these things in mind :-

- Tech Stack :- HTML / CSS / Bootstrap
- If you have any doubts you can ask here only.
- Please mention the issue name in your PR.

**Comment by SudhansuuRanjan** [comment]
I want to work on this issue please assign it to me.

**Comment by harshagrawal523** [comment]
> I want to work on this issue please assign it to me.

Okay! Assigning you
