### ISSUE TITLE
Add New Templates for Portfolio

### ISSUE THREAD

**Issue by GunjanDhanuka** [harshagrawal523/Portfolyser#24]
Currently, we have only one template (TooMinimal). We would appreciate if you add more templates, for eg: Developer portfolio, Student portfolio, Research portfolio, etc.

You have to add ONLY the HTML files for different portfolios to the `templates` folder as part of this issue. We will create another issue for the .ejs files later. Make sure to keep all the styling and scripts within the HTML file only.

**Comment by shmiitg** [comment]
I would like to work on this

**Comment by harshagrawal523** [comment]
Okay!

**Comment by harshagrawal523** [comment]
> I would like to work on this

Do you want to work on this now?

**Comment by shmiitg** [comment]
I have made three templates (developer, research, student)

Developer
![Screenshot 2021-12-08 at 00-47-25 Developer](https://user-images.githubusercontent.com/70333141/145093018-c39dcc83-bd58-4ca2-b166-6c578d53cf2c.png)

Research 
![Screenshot 2021-12-08 at 00-49-43 Document](https://user-images.githubusercontent.com/70333141/145093172-90d20c7a-095c-4538-a43f-f4c96b540ff6.png)

Student
![Screenshot 2021-12-08 at 00-52-15 Document](https://user-images.githubusercontent.com/70333141/145093314-41a1ff74-af98-4ebf-8307-90454f016b47.png)

Please check if its fine

**Comment by harshagrawal523** [comment]
> I have made three templates (developer, research, student)
> 
> Developer ![Screenshot 2021-12-08 at 00-47-25 Developer](https://user-images.githubusercontent.com/70333141/145093018-c39dcc83-bd58-4ca2-b166-6c578d53cf2c.png)
> 
> Research ![Screenshot 2021-12-08 at 00-49-43 Document](https://user-images.githubusercontent.com/70333141/145093172-90d20c7a-095c-4538-a43f-f4c96b540ff6.png)
> 
> Student ![Screenshot 2021-12-08 at 00-52-15 Document](https://user-images.githubusercontent.com/70333141/145093314-41a1ff74-af98-4ebf-8307-90454f016b47.png)
> 
> Please check if its fine

This is great but with template we meant frontend , like we have a template on `/final` like that we need different fronend templates.

**Comment by shmiitg** [comment]
ok i got it

**Comment by shmiitg** [comment]
ok I got it. For this issue you can assign someone else. I will take some other issue.

**Comment by Tanishqmalu** [comment]
Claim.

**Comment by GunjanDhanuka** [comment]
I think we can keep this issue open incase people wish to add more templates.

**Comment by akshatjain1004** [comment]
Hi can I work on this issue?

**Comment by harshagrawal523** [comment]
> Hi can I work on this issue? @GunjanDhanuka @harshagrawal523

sure you can
