### ISSUE TITLE
Add Pull Request and Issue template

### ISSUE THREAD

**Issue by Pranav108** [harshagrawal523/Portfolyser#28]
Adding a pull request and issue template will make this repository more structured and will help beginner to get started here.

**Comment by ArchismanKarmakar** [comment]
> Adding a pull request and issue template will make this repository more structured and will help beginner to get started here.

i have done this

**Comment by ArchismanKarmakar** [comment]
> Adding a pull request and issue template will make this repository more structured and will help beginner to get started here.

i have another PR running so what shall i do?

**Comment by Pranav108** [comment]
> > Adding a pull request and issue template will make this repository more structured and will help beginner to get started here.
> 
> i have another PR running so what shall i do?

@harshagrawal523 can tell you about that.

**Comment by ArchismanKarmakar** [comment]
> > > Adding a pull request and issue template will make this repository more structured and will help beginner to get started here.
> > 
> > 
> > i have another PR running so what shall i do?
> 
> @harshagrawal523 can tell you about that.

sir please check PR #27 that was my last issue i was working

**Comment by ArchismanKarmakar** [comment]
> Adding a pull request and issue template will make this repository more structured and will help beginner to get started here.

#30 done

**Comment by harshagrawal523** [comment]
> > Adding a pull request and issue template will make this repository more structured and will help beginner to get started here.
> 
> #30 done

Thank you for this @ArchismanKarmakar @Pranav108 !

**Comment by ArchismanKarmakar** [comment]
> > > Adding a pull request and issue template will make this repository more structured and will help beginner to get started here.
> > 
> > #30 done
> 
> Thank you for this @ArchismanKarmakar @Pranav108 !

I have another PR update home.ejs please check that

**Comment by ArchismanKarmakar** [comment]
> > > Adding a pull request and issue template will make this repository more structured and will help beginner to get started here.
> > 
> > 
> > #30 done
> 
> Thank you for this @ArchismanKarmakar @Pranav108 !

@harshagrawal523 what points did i get for it sir?? can you please tell me?

**Comment by codingiitg** [comment]
> > > > Adding a pull request and issue template will make this repository more structured and will help beginner to get started here.
> > > 
> > > 
> > > #30 done
> > 
> > 
> > Thank you for this @ArchismanKarmakar @Pranav108 !
> 
> @harshagrawal523 what points did i get for this issues #28 & #27 sir?? can you please tell me?

as both of them were easy issues , you will get 10 points in total , 5 for each

**Comment by ArchismanKarmakar** [comment]
> > > > > Adding a pull request and issue template will make this repository more structured and will help beginner to get started here.
> > > > 
> > > > 
> > > > #30 done
> > > 
> > > 
> > > Thank you for this @ArchismanKarmakar @Pranav108 !
> > 
> > @harshagrawal523 what points did i get for this issues #28 & #27 sir?? can you please tell me?
> 
> as both of them were easy issues , you will get 10 points in total , 5 for each

Okay sir thank you
