### ISSUE TITLE
Login & Register links doesn't work

### ISSUE THREAD

**Issue by harshagrawal523** [harshagrawal523/Portfolyser#3]
The Login/Register link on the **homepage** is not working and needs links to be added. Please go through the code to get the appropriate hrefs .

- Please mention the issue name in your PR
- If you have any doubts ask here only.

**Comment by akshatjain1004** [comment]
I'd like to work on this

**Comment by harshagrawal523** [comment]
> I'd like to work on this

Okay ! Assigning you!
