### ISSUE TITLE
Add frontend to Introduction forms page( The theme of the website should be same)

### ISSUE THREAD

**Issue by harshagrawal523** [harshagrawal523/Portfolyser#32]
# Description
Provide a clear description of the issue :-
Currently the forms section which takes information about your personal bio and all , it is very basic and has no frontend element.

# Screenshot
<img width="1132" alt="Screenshot 2021-12-14 at 22 56 52" src="https://user-images.githubusercontent.com/77069304/146049051-deac471f-ef2d-48ff-af2c-f8cd360fb96f.png">

# References
`/intro`

**Comment by ArchismanKarmakar** [comment]
> 

i want to work, please assign me, i may be late because my exams are going on, so please pardon me for late PR

**Comment by harshagrawal523** [comment]
Okay you can

**Comment by 1ananya3** [comment]
Can I solve this issue?

**Comment by harshagrawal523** [comment]
> Can I solve this issue?

I will opening a simillar issue you can try that , this has been assigned

**Comment by ArchismanKarmakar** [comment]
> # Description
> Provide a clear description of the issue :- Currently the forms section which takes information about your personal bio and all , it is very basic and has no frontend element.
> 
> # Screenshot
> <img alt="Screenshot 2021-12-14 at 22 56 52" width="1132" src="https://user-images.githubusercontent.com/77069304/146049051-deac471f-ef2d-48ff-af2c-f8cd360fb96f.png">
> 
> # References
> `/intro`

#34 job done

**Comment by 1ananya3** [comment]
> > Can I solve this issue?
> 
> I will opening a simillar issue you can try that , this has been assigned

please assign me on that.

**Comment by harshagrawal523** [comment]
> > > Can I solve this issue?
> > 
> > 
> > I will opening a simillar issue you can try that , this has been assigned
> 
> please assign me on that.

Okay I will directly assign you on that
