### ISSUE TITLE
Add frontend to education/work experience page( The theme of the website should be same) 

### ISSUE THREAD

**Issue by harshagrawal523** [harshagrawal523/Portfolyser#33]
##Description
Provide a clear description of the issue
Currently the forms section which takes information about your work experience and education and all , it is very basic and has no frontend element.

## Screenshot
<img width="1330" alt="Screenshot 2021-12-15 at 12 01 43" src="https://user-images.githubusercontent.com/77069304/146135535-b223eb09-d582-430c-a967-d966913a3649.png">

## References
`/education`

**Comment by rt-001** [comment]
i want to work, please assign me

**Comment by nadavmza** [comment]
Can you assign me?

**Comment by 1ananya3** [comment]
please assign me .I want to work on this.

**Comment by ArchismanKarmakar** [comment]
> ##Description
> Provide a clear description of the issue
> Currently the forms section which takes information about your work experience and education and all , it is very basic and has no frontend element.
> 
> ## Screenshot
> <img width="1330" alt="Screenshot 2021-12-15 at 12 01 43" src="https://user-images.githubusercontent.com/77069304/146135535-b223eb09-d582-430c-a967-d966913a3649.png">
> 
> 
> ## References
> `/education`
> 

I want to work with this. Please assign me

**Comment by harshagrawal523** [comment]
@rt-001 @nadavmza @1ananya3 @ArchismanKarmakar  who want to work on this , I was not active since some days so I missed the messages can some one confirm again who wants to work on this issue?

**Comment by ArchismanKarmakar** [comment]
> @rt-001 @nadavmza @1ananya3 @ArchismanKarmakar  who want to work on this , I was not active since some days so I missed the messages can some one confirm again who wants to work on this issue?
> 

Bhaiya you can assign me i am starting to work on this

**Comment by harshagrawal523** [comment]
> > @rt-001 @nadavmza @1ananya3 @ArchismanKarmakar  who want to work on this , I was not active since some days so I missed the messages can some one confirm again who wants to work on this issue?
> 
> Bhaiya you can assign me i am starting to work on this

okay

**Comment by 1ananya3** [comment]
Can you assign me bhaiya ? I have sent you a message on discord also.

**Comment by ArchismanKarmakar** [comment]
> > > @rt-001 @nadavmza @1ananya3 @ArchismanKarmakar  who want to work on this , I was not active since some days so I missed the messages can some one confirm again who wants to work on this issue?
> > 
> > 
> > Bhaiya you can assign me i am starting to work on this
> 
> okay

#34 also solved @harshagrawal523

**Comment by harshagrawal523** [comment]
@1ananya3 you can also work on this

**Comment by 1ananya3** [comment]
I have created a new PR for this issue .Please review it . Thank you.

**Comment by harshagrawal523** [comment]
> I have created a new PR for this issue .Please review it . Thank you.

Okay I will
