### ISSUE TITLE
Issues with `/intro` page.

### ISSUE THREAD

**Issue by letsintegreat** [harshagrawal523/Portfolyser#37]
The submit button on `/intro` no longer updates the user's intro in the database.
Also, the name field no longer shows the currently added name~

Both of them were working till my PR #26, it seems some contributor broke it mistakenly.

![image](https://user-images.githubusercontent.com/37345795/147590199-1d0bdc58-8cf8-4874-ac83-16a86ff9fc6d.png)

**Comment by letsintegreat** [comment]
I'd like to work on this issue.

**Comment by letsintegreat** [comment]
Also, why is there this code in `intro.ejs`?
![image](https://user-images.githubusercontent.com/37345795/147590585-423b9425-33f1-4719-8076-774c96fc4644.png)

I think `/intro` is only accessible when you are logged in.
Is there any specific purpose of this code, or is it just redundant?
If the latter is the case, I'd remove it in the PR too.

**Comment by letsintegreat** [comment]
- While improving the UI, some contributor removed name property from each input, so we can no longer get the values of input in the way we were getting before
- <form> tag never ends :)))

**Comment by harshagrawal523** [comment]
I guess I didnt check it properly , thanks for this
