### ISSUE TITLE
Scraping error 

### ISSUE THREAD

**Issue by harshagrawal523** [harshagrawal523/Portfolyser#4]
When trying to scrap the final file in .html , a type error is coming and it's not getting the desired scraped data. 

Steps to recreate the error (provided you have installed the code properly)
1. After logging in , fill the information page.
2. Go on "click here to see the final website"
3. In the search bar search the url "http://localhost:3100/render"
4. The error will be in your console.

If you have any doubts ask here. Please mention the issue name in your PR.

**Comment by ArchismanKarmakar** [comment]
Sir I want to work in this issue but I am getting a error in setting up:

C:\Users\Archisman\Desktop\Portfolyser-main\node_modules\mongodb-connection-string-url\lib\index.js:66
            throw new MongoParseError(`Invalid connection string "${uri}"`);
                  ^

MongoParseError: Invalid connection string "<your mongodb url for connection>"
    at new ConnectionString (C:\Users\Archisman\Desktop\Portfolyser-main\node_modules\mongodb-connection-string-url\lib\index.js:66:19)
    at parseOptions (C:\Users\Archisman\Desktop\Portfolyser-main\node_modules\mongodb\lib\connection_string.js:210:17)
    at new MongoClient (C:\Users\Archisman\Desktop\Portfolyser-main\node_modules\mongodb\lib\mongo_client.js:62:63)
    at Function.connect (C:\Users\Archisman\Desktop\Portfolyser-main\node_modules\mongodb\lib\mongo_client.js:184:33)
    at new MongoStore (C:\Users\Archisman\Desktop\Portfolyser-main\node_modules\connect-mongo\build\main\lib\MongoStore.js:110:46)
    at Function.create (C:\Users\Archisman\Desktop\Portfolyser-main\node_modules\connect-mongo\build\main\lib\MongoStore.js:136:16)
    at Object.<anonymous> (C:\Users\Archisman\Desktop\Portfolyser-main\app.js:36:27)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)

Please Help me solve the issue.

**Comment by letsintegreat** [comment]
@ArchismanKarmakar I had the exact same error. Most probably, the mongodb url in `config.env` is incorrect.

**Comment by letsintegreat** [comment]
@ArchismanKarmakar 
Download and add the address to `mongo` in `PATH` environmental variable. Then run `mongo` command in command prompt.

You would see something like this:

>C:\Users\Harshit>mongo
MongoDB shell version v5.0.4
connecting to: mongodb://127.0.0.1:27017/?compressors=disabled&gssapiServiceName=mongodb

You have to replace `<your mongodb url for connection>` with the part before `/?compressors` (in this case it is: `mongodb://127.0.0.1:27017`)

**Comment by letsintegreat** [comment]
I'd like to work on this issue.

**Comment by ArchismanKarmakar** [comment]
> @ArchismanKarmakar Download and add the address to `mongo` in `PATH` environmental variable. Then run `mongo` command in command prompt.
> 
> You would see something like this:
> 
> > C:\Users\Harshit>mongo
> > MongoDB shell version v5.0.4
> > connecting to: mongodb://127.0.0.1:27017/?compressors=disabled&gssapiServiceName=mongodb
> 
> You have to replace `<your mongodb url for connection>` with the part before `/?compressors` (in this case it is: `mongodb://127.0.0.1:27017`)

thanks

**Comment by ArchismanKarmakar** [comment]
> Sir I want to work in this issue but I am getting a error in setting up:
> 
> PS C:\Users\Archisman\Desktop\Portfolyser-main> node app.js body-parser deprecated undefined extended: provide extended option routes\index.js:4:20 listening at 3100 C:\Users\Archisman\Desktop\Portfolyser-main\node_modules\mongodb-connection-string-url\lib\index.js:66 throw new MongoParseError(`Invalid connection string "${uri}"`); ^
> 
> MongoParseError: Invalid connection string "" at new ConnectionString (C:\Users\Archisman\Desktop\Portfolyser-main\node_modules\mongodb-connection-string-url\lib\index.js:66:19) at parseOptions (C:\Users\Archisman\Desktop\Portfolyser-main\node_modules\mongodb\lib\connection_string.js:210:17) at new MongoClient (C:\Users\Archisman\Desktop\Portfolyser-main\node_modules\mongodb\lib\mongo_client.js:62:63) at Function.connect (C:\Users\Archisman\Desktop\Portfolyser-main\node_modules\mongodb\lib\mongo_client.js:184:33) at new MongoStore (C:\Users\Archisman\Desktop\Portfolyser-main\node_modules\connect-mongo\build\main\lib\MongoStore.js:110:46) at Function.create (C:\Users\Archisman\Desktop\Portfolyser-main\node_modules\connect-mongo\build\main\lib\MongoStore.js:136:16) at Object. (C:\Users\Archisman\Desktop\Portfolyser-main\app.js:36:27) at Module._compile (node:internal/modules/cjs/loader:1101:14) at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10) at Module.load (node:internal/modules/cjs/loader:981:32) PS C:\Users\Archisman\Desktop\Portfolyser-main>
> 
> Please Help me solve the issue.

i am not able to find any kind of error. i have followed all the mentioned steps. i am using firefox developer edition
![123](https://user-images.githubusercontent.com/92569441/144758306-cb3d1c0d-49d3-40b2-bfab-cb89d99342ea.png)

**Comment by ArchismanKarmakar** [comment]
> When trying to scrap the final file in .html , a type error is coming and it's not getting the desired scraped data.
> 
> Steps to recreate the error (provided you have installed the code properly)
> 
> 1. After logging in , fill the information page.
> 2. Go on "click here to see the final website"
> 3. In the search bar search the url "http://localhost:3100/render"
> 4. The error will be in your console.
> 
> If you have any doubts ask here. Please mention the issue name in your PR.

no error even in google chrome or edge

**Comment by harshagrawal523** [comment]
> > Sir I want to work in this issue but I am getting a error in setting up:
> > PS C:\Users\Archisman\Desktop\Portfolyser-main> node app.js body-parser deprecated undefined extended: provide extended option routes\index.js:4:20 listening at 3100 C:\Users\Archisman\Desktop\Portfolyser-main\node_modules\mongodb-connection-string-url\lib\index.js:66 throw new MongoParseError(`Invalid connection string "${uri}"`); ^
> > MongoParseError: Invalid connection string "" at new ConnectionString (C:\Users\Archisman\Desktop\Portfolyser-main\node_modules\mongodb-connection-string-url\lib\index.js:66:19) at parseOptions (C:\Users\Archisman\Desktop\Portfolyser-main\node_modules\mongodb\lib\connection_string.js:210:17) at new MongoClient (C:\Users\Archisman\Desktop\Portfolyser-main\node_modules\mongodb\lib\mongo_client.js:62:63) at Function.connect (C:\Users\Archisman\Desktop\Portfolyser-main\node_modules\mongodb\lib\mongo_client.js:184:33) at new MongoStore (C:\Users\Archisman\Desktop\Portfolyser-main\node_modules\connect-mongo\build\main\lib\MongoStore.js:110:46) at Function.create (C:\Users\Archisman\Desktop\Portfolyser-main\node_modules\connect-mongo\build\main\lib\MongoStore.js:136:16) at Object. (C:\Users\Archisman\Desktop\Portfolyser-main\app.js:36:27) at Module._compile (node:internal/modules/cjs/loader:1101:14) at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10) at Module.load (node:internal/modules/cjs/loader:981:32) PS C:\Users\Archisman\Desktop\Portfolyser-main>
> > Please Help me solve the issue.
> 
> i am not able to find any kind of error. i have followed all the mentioned steps. i am using firefox developer edition ![123](https://user-images.githubusercontent.com/92569441/144758306-cb3d1c0d-49d3-40b2-bfab-cb89d99342ea.png)

**Comment by harshagrawal523** [comment]
> > When trying to scrap the final file in .html , a type error is coming and it's not getting the desired scraped data.
> > Steps to recreate the error (provided you have installed the code properly)
> > 
> > 1. After logging in , fill the information page.
> > 2. Go on "click here to see the final website"
> > 3. In the search bar search the url "http://localhost:3100/render"
> > 4. The error will be in your console.
> > 
> > If you have any doubts ask here. Please mention the issue name in your PR.
> 
> no error even in google chrome or edge

you are not getting the error?

**Comment by harshagrawal523** [comment]
> > > Sir I want to work in this issue but I am getting a error in setting up:
> > > PS C:\Users\Archisman\Desktop\Portfolyser-main> node app.js body-parser deprecated undefined extended: provide extended option routes\index.js:4:20 listening at 3100 C:\Users\Archisman\Desktop\Portfolyser-main\node_modules\mongodb-connection-string-url\lib\index.js:66 throw new MongoParseError(`Invalid connection string "${uri}"`); ^
> > > MongoParseError: Invalid connection string "" at new ConnectionString (C:\Users\Archisman\Desktop\Portfolyser-main\node_modules\mongodb-connection-string-url\lib\index.js:66:19) at parseOptions (C:\Users\Archisman\Desktop\Portfolyser-main\node_modules\mongodb\lib\connection_string.js:210:17) at new MongoClient (C:\Users\Archisman\Desktop\Portfolyser-main\node_modules\mongodb\lib\mongo_client.js:62:63) at Function.connect (C:\Users\Archisman\Desktop\Portfolyser-main\node_modules\mongodb\lib\mongo_client.js:184:33) at new MongoStore (C:\Users\Archisman\Desktop\Portfolyser-main\node_modules\connect-mongo\build\main\lib\MongoStore.js:110:46) at Function.create (C:\Users\Archisman\Desktop\Portfolyser-main\node_modules\connect-mongo\build\main\lib\MongoStore.js:136:16) at Object. (C:\Users\Archisman\Desktop\Portfolyser-main\app.js:36:27) at Module._compile (node:internal/modules/cjs/loader:1101:14) at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10) at Module.load (node:internal/modules/cjs/loader:981:32) PS C:\Users\Archisman\Desktop\Portfolyser-main>
> > > Please Help me solve the issue.
> > 
> > 
> > i am not able to find any kind of error. i have followed all the mentioned steps. i am using firefox developer edition ![123](https://user-images.githubusercontent.com/92569441/144758306-cb3d1c0d-49d3-40b2-bfab-cb89d99342ea.png)

I would you use mongoDB atlas , you can use the below video as reference and setup using this

https://www.youtube.com/watch?v=bxsemcrY4gQ&list=PL4cUxeGkcC9jsz4LDYc6kv3ymONOKxwBU&index=10

**Comment by ArchismanKarmakar** [comment]
> > > > Sir I want to work in this issue but I am getting a error in setting up:
> > > > PS C:\Users\Archisman\Desktop\Portfolyser-main> node app.js body-parser deprecated undefined extended: provide extended option routes\index.js:4:20 listening at 3100 C:\Users\Archisman\Desktop\Portfolyser-main\node_modules\mongodb-connection-string-url\lib\index.js:66 throw new MongoParseError(`Invalid connection string "${uri}"`); ^
> > > > MongoParseError: Invalid connection string "" at new ConnectionString (C:\Users\Archisman\Desktop\Portfolyser-main\node_modules\mongodb-connection-string-url\lib\index.js:66:19) at parseOptions (C:\Users\Archisman\Desktop\Portfolyser-main\node_modules\mongodb\lib\connection_string.js:210:17) at new MongoClient (C:\Users\Archisman\Desktop\Portfolyser-main\node_modules\mongodb\lib\mongo_client.js:62:63) at Function.connect (C:\Users\Archisman\Desktop\Portfolyser-main\node_modules\mongodb\lib\mongo_client.js:184:33) at new MongoStore (C:\Users\Archisman\Desktop\Portfolyser-main\node_modules\connect-mongo\build\main\lib\MongoStore.js:110:46) at Function.create (C:\Users\Archisman\Desktop\Portfolyser-main\node_modules\connect-mongo\build\main\lib\MongoStore.js:136:16) at Object. (C:\Users\Archisman\Desktop\Portfolyser-main\app.js:36:27) at Module._compile (node:internal/modules/cjs/loader:1101:14) at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10) at Module.load (node:internal/modules/cjs/loader:981:32) PS C:\Users\Archisman\Desktop\Portfolyser-main>
> > > > Please Help me solve the issue.
> > > 
> > > 
> > > i am not able to find any kind of error. i have followed all the mentioned steps. i am using firefox developer edition ![123](https://user-images.githubusercontent.com/92569441/144758306-cb3d1c0d-49d3-40b2-bfab-cb89d99342ea.png)
> 
> I would you use mongoDB atlas , you can use the below video as reference and setup using this
> 
> https://www.youtube.com/watch?v=bxsemcrY4gQ&list=PL4cUxeGkcC9jsz4LDYc6kv3ymONOKxwBU&index=10

okay i have to check out mongodb atlas then, i have never used it.

**Comment by ArchismanKarmakar** [comment]
> > > > Sir I want to work in this issue but I am getting a error in setting up:
> > > > PS C:\Users\Archisman\Desktop\Portfolyser-main> node app.js body-parser deprecated undefined extended: provide extended option routes\index.js:4:20 listening at 3100 C:\Users\Archisman\Desktop\Portfolyser-main\node_modules\mongodb-connection-string-url\lib\index.js:66 throw new MongoParseError(`Invalid connection string "${uri}"`); ^
> > > > MongoParseError: Invalid connection string "" at new ConnectionString (C:\Users\Archisman\Desktop\Portfolyser-main\node_modules\mongodb-connection-string-url\lib\index.js:66:19) at parseOptions (C:\Users\Archisman\Desktop\Portfolyser-main\node_modules\mongodb\lib\connection_string.js:210:17) at new MongoClient (C:\Users\Archisman\Desktop\Portfolyser-main\node_modules\mongodb\lib\mongo_client.js:62:63) at Function.connect (C:\Users\Archisman\Desktop\Portfolyser-main\node_modules\mongodb\lib\mongo_client.js:184:33) at new MongoStore (C:\Users\Archisman\Desktop\Portfolyser-main\node_modules\connect-mongo\build\main\lib\MongoStore.js:110:46) at Function.create (C:\Users\Archisman\Desktop\Portfolyser-main\node_modules\connect-mongo\build\main\lib\MongoStore.js:136:16) at Object. (C:\Users\Archisman\Desktop\Portfolyser-main\app.js:36:27) at Module._compile (node:internal/modules/cjs/loader:1101:14) at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10) at Module.load (node:internal/modules/cjs/loader:981:32) PS C:\Users\Archisman\Desktop\Portfolyser-main>
> > > > Please Help me solve the issue.
> > > 
> > > 
> > > i am not able to find any kind of error. i have followed all the mentioned steps. i am using firefox developer edition ![123](https://user-images.githubusercontent.com/92569441/144758306-cb3d1c0d-49d3-40b2-bfab-cb89d99342ea.png)
> 
> I would you use mongoDB atlas , you can use the below video as reference and setup using this
> 
> https://www.youtube.com/watch?v=bxsemcrY4gQ&list=PL4cUxeGkcC9jsz4LDYc6kv3ymONOKxwBU&index=10

what i got in terminal: 

PS C:\Users\Archisman\Desktop\Portfolyser-main> node app.js
body-parser deprecated undefined extended: provide extended option routes\index.js:4:20
listening at 3100
GET / 200 19.413 ms - 207
GET /final 200 7.417 ms - 4732
GET /render - - ms - -

**Comment by ArchismanKarmakar** [comment]
> > > > Sir I want to work in this issue but I am getting a error in setting up:
> > > > PS C:\Users\Archisman\Desktop\Portfolyser-main> node app.js body-parser deprecated undefined extended: provide extended option routes\index.js:4:20 listening at 3100 C:\Users\Archisman\Desktop\Portfolyser-main\node_modules\mongodb-connection-string-url\lib\index.js:66 throw new MongoParseError(`Invalid connection string "${uri}"`); ^
> > > > MongoParseError: Invalid connection string "" at new ConnectionString (C:\Users\Archisman\Desktop\Portfolyser-main\node_modules\mongodb-connection-string-url\lib\index.js:66:19) at parseOptions (C:\Users\Archisman\Desktop\Portfolyser-main\node_modules\mongodb\lib\connection_string.js:210:17) at new MongoClient (C:\Users\Archisman\Desktop\Portfolyser-main\node_modules\mongodb\lib\mongo_client.js:62:63) at Function.connect (C:\Users\Archisman\Desktop\Portfolyser-main\node_modules\mongodb\lib\mongo_client.js:184:33) at new MongoStore (C:\Users\Archisman\Desktop\Portfolyser-main\node_modules\connect-mongo\build\main\lib\MongoStore.js:110:46) at Function.create (C:\Users\Archisman\Desktop\Portfolyser-main\node_modules\connect-mongo\build\main\lib\MongoStore.js:136:16) at Object. (C:\Users\Archisman\Desktop\Portfolyser-main\app.js:36:27) at Module._compile (node:internal/modules/cjs/loader:1101:14) at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10) at Module.load (node:internal/modules/cjs/loader:981:32) PS C:\Users\Archisman\Desktop\Portfolyser-main>
> > > > Please Help me solve the issue.
> > > 
> > > 
> > > i am not able to find any kind of error. i have followed all the mentioned steps. i am using firefox developer edition ![123](https://user-images.githubusercontent.com/92569441/144758306-cb3d1c0d-49d3-40b2-bfab-cb89d99342ea.png)
> 
> I would you use mongoDB atlas , you can use the below video as reference and setup using this
> 
> https://www.youtube.com/watch?v=bxsemcrY4gQ&list=PL4cUxeGkcC9jsz4LDYc6kv3ymONOKxwBU&index=10

can you please provide a screenshot of the bug?

**Comment by harshagrawal523** [comment]
> > > > > Sir I want to work in this issue but I am getting a error in setting up:
> > > > > PS C:\Users\Archisman\Desktop\Portfolyser-main> node app.js body-parser deprecated undefined extended: provide extended option routes\index.js:4:20 listening at 3100 C:\Users\Archisman\Desktop\Portfolyser-main\node_modules\mongodb-connection-string-url\lib\index.js:66 throw new MongoParseError(`Invalid connection string "${uri}"`); ^
> > > > > MongoParseError: Invalid connection string "" at new ConnectionString (C:\Users\Archisman\Desktop\Portfolyser-main\node_modules\mongodb-connection-string-url\lib\index.js:66:19) at parseOptions (C:\Users\Archisman\Desktop\Portfolyser-main\node_modules\mongodb\lib\connection_string.js:210:17) at new MongoClient (C:\Users\Archisman\Desktop\Portfolyser-main\node_modules\mongodb\lib\mongo_client.js:62:63) at Function.connect (C:\Users\Archisman\Desktop\Portfolyser-main\node_modules\mongodb\lib\mongo_client.js:184:33) at new MongoStore (C:\Users\Archisman\Desktop\Portfolyser-main\node_modules\connect-mongo\build\main\lib\MongoStore.js:110:46) at Function.create (C:\Users\Archisman\Desktop\Portfolyser-main\node_modules\connect-mongo\build\main\lib\MongoStore.js:136:16) at Object. (C:\Users\Archisman\Desktop\Portfolyser-main\app.js:36:27) at Module._compile (node:internal/modules/cjs/loader:1101:14) at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10) at Module.load (node:internal/modules/cjs/loader:981:32) PS C:\Users\Archisman\Desktop\Portfolyser-main>
> > > > > Please Help me solve the issue.
> > > > 
> > > > 
> > > > i am not able to find any kind of error. i have followed all the mentioned steps. i am using firefox developer edition ![123](https://user-images.githubusercontent.com/92569441/144758306-cb3d1c0d-49d3-40b2-bfab-cb89d99342ea.png)
> > 
> > 
> > I would you use mongoDB atlas , you can use the below video as reference and setup using this
> > https://www.youtube.com/watch?v=bxsemcrY4gQ&list=PL4cUxeGkcC9jsz4LDYc6kv3ymONOKxwBU&index=10
> 
> can you please provide a screenshot of the bug?

Come to the discord page of our project , @letsintegreat has shared the error screenshot
