### ISSUE TITLE
Add form for project links

### ISSUE THREAD

**Issue by harshagrawal523** [harshagrawal523/Portfolyser#5]
Create a working form just like introduction form through which a user can add all his project links. 
One field should be of email and that should contain the same email the user entered while log in.

- If you have any doubts ask here only
- Please mention the issue name in your PR
- You need to add model , ejs and routes in order for it to work properly

**Comment by SiddharthaKR** [comment]
Hey can you assign me this issue

**Comment by harshagrawal523** [comment]
> Hey can you assign me this issue
okay!

**Comment by harshagrawal523** [comment]
Are you working on this @SiddharthaKR ?

**Comment by shmiitg** [comment]
Do we need to style the page also? If not, you can assign me this issue

**Comment by codingiitg** [comment]
> Do we need to style the page also? If not, you can assign me this issue

I'll wait for today for @SiddharthaKR's reply , otherwise I will assign you

**Comment by shmiitg** [comment]
> > Do we need to style the page also? If not, you can assign me this issue
> 
> I'll wait for today for @SiddharthaKR's reply , otherwise I will assign you

Ok

**Comment by shmiitg** [comment]
Can I take this issue now?

**Comment by shmiitg** [comment]
Do we need the email field in form?  As user has already logged in and we can directly get the email from there.

> Create a working form just like introduction form through which a user can add all his project links. One field should be of email and that should contain the same email the user entered while log in.
> 
> * If you have any doubts ask here only
> * Please mention the issue name in your PR
> * You need to add model , ejs and routes in order for it to work properly

**Comment by harshagrawal523** [comment]
> n directly get the email

yes you can directly get the email, you dont need to have it in form but in database you need  to have an email field otherwise we can't track the the fields.

**Comment by shmiitg** [comment]
> > n directly get the email
> 
> yes you can directly get the email, you dont need to have it in form but in database you need to have an email field otherwise we can't track the the fields.

ok
