### ISSUE TITLE
Home page needs frontend enhancement

### ISSUE THREAD

**Issue by harshagrawal523** [harshagrawal523/Portfolyser#6]
The home page is very basic and just has the form element and nothing else. Enhance the frontend of home page , nothing very fancy just minimal enhancement. Please keep these things in mind :-

- Tech Stack :- HTML / CSS / Bootstrap
- If you have any doubts you can ask here only.
- Please mention the issue name in your PR.

**Comment by shmiitg** [comment]
I want to work on this issue. Please assign to me

**Comment by harshagrawal523** [comment]
> I want to work on this issue. Please assign to me

yes you can

**Comment by harshagrawal523** [comment]
This is still open to more new ideas for homepage UI!

**Comment by shmiitg** [comment]
ok I will try to enhance it

**Comment by harshagrawal523** [comment]
> ok I will try to enhance it

okay !
