### ISSUE TITLE
Add login using google functionality

### ISSUE THREAD

**Issue by harshagrawal523** [harshagrawal523/Portfolyser#7]
There is only normal login in which you need to register a email , add auth through which a user can login using google too.

- Please mention issue name in your PR
- If you have any issues ask here

**Comment by letsintegreat** [comment]
I'd like to work on this issue.

**Comment by harshagrawal523** [comment]
> I'd like to work on this issue.

Okay ! Assigning you

**Comment by harshagrawal523** [comment]
Great work @letsintegreat
